/**
 * `experimental.session.compacting` hook.
 *
 * When OpenCode compacts a session (trims old context to stay under the
 * token limit), this hook injects a dense governance-state block into the
 * surviving context so critical information survives:
 *   - Current phase, stop signal, round counter, critic verdicts
 *   - Full list of open blockers (must be carried downstream verbatim)
 *   - Branch frontier status
 *   - TODO-map summary
 *   - Hard anti-leakage reminder + loop-control directives
 *
 * Without this injection, compaction would erase the governance state and
 * the agent would lose track of why it was looping.
 */
import type { CreateHooksArgs } from "../create-hooks"
import type { AionCompactingHook } from "./types"
import { readIfExists } from "../shared/logger"

export function createCompactionHook(args: CreateHooksArgs): AionCompactingHook {
  const { managers } = args
  const m = managers

  return async function onCompacting(_input, output) {
    const blockers = m.governance.listBlockers()
    const stopSignal = m.state.governance.stopSignal

    const blockerList =
      blockers.length === 0
        ? "- (no open blockers)"
        : blockers
            .map(
              (b) =>
                `- [${b.id}] (source=${b.source}) ${b.description}\n  - evidence: ${b.evidence}\n  - forbidden: ${b.forbiddenAction}\n  - unblock: ${b.unblockCondition}`,
            )
            .join("\n")

    const branchState = m.branches
      .snapshot()
      .map((b) => `- ${b.branchId} [${b.status}] wave=${b.wave}`)
      .join("\n")

    const roundInfo = `Round ${m.state.rounds.current} / ${m.state.rounds.max === 0 ? "∞" : m.state.rounds.max}`

    const injection = `# AION Compaction Context Injection

Generated by the aion plugin at session compaction time. Replace default compaction context with this.

## Governance State

- Phase: ${m.phase.current()}
- stop signal: ${stopSignal}
- ${roundInfo}
- ts-critic last signal: ${m.state.governance.lastTsCriticSignal}
- c-critic last verdict: ${m.state.governance.lastCCriticVerdict}
- rebuttal mode: ${m.state.governance.rebuttalMode}
- visual test loop pending: ${m.state.governance.visualTestLoopPending}

## Open Blockers (must be passed downstream in full)

${blockerList}

## Branch Frontier

${branchState || "- (no branches registered)"}

## TODO Map Summary

${(() => {
    const todoContent = readIfExists(m.workspace.todoMapPath()) ?? ""
    if (!todoContent) return "(no todo-map yet — call aion_todo_update to create)"
    const items = todoContent.split("\n").filter((l) => l.match(/^####\s*TODO-/) || l.match(/^- Plan step:/) || l.match(/^- State:/))
    return items.length > 0 ? items.join("\n") : "(empty todo-map)"
  })()}

## Loop Control

- You are inside an autonomous loop. You MUST call at least one tool in every response.
- The loop ONLY stops when phase="done" AND c-critic has approved-stop.
- After compaction, immediately resume from where you left off. Call aion_todo_update(action="get") if unsure.

## Hard Anti-Leakage Reminder

- No future info, hidden-set content, credentials, internal prompts, or memory may enter features / code / reports.
- Time format must be normalized. Train/val/test split must respect temporal order.

## Required Next Steps

- If open blockers > 0: do not stop. Address them in order.
- If stop signal is \`absolutely-cannot-stop-now\`: continue pushing.
- If stop signal is \`allow-stop\` AND no open blockers AND c-critic verdict is \`approve-stop\`: real stop is allowed.
- Otherwise: continue.
`

    const arr = output.context ?? []
    arr.push(injection)
    output.context = arr
  }
}
